# Generated by Django 3.2.18 on 2023-04-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='user_id',
            new_name='user',
        ),
    ]
